version: '3.8'

services:
  inventory-api:
    build: .
    container_name: inventory-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always

  inventory-worker:
    build: .
    container_name: inventory-worker
    command: ["uv", "run", "python", "run_inventory_reservation_consumer.py"]
    env_file:
      - .env
    restart: always

  inventory-migration:
    build: .
    container_name: inventory-migration
    command: ["uv", "run", "alembic", "upgrade", "head"]
    env_file:
      - .env