sonar.projectKey=ARCN-2026-1_inventory-service
sonar.organization=arcn-2026-1


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=inventory-service
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

sonar.projectName=inventory-service
sonar.sources=internal,main.py
sonar.tests=test
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/.git/**,**/.github/**,**/docs/**,**/.venv/**,**/__pycache__/**,**/.env.local,**/alembic.ini
sonar.test.inclusions=**/test/**,**/*test*.py
sonar.python.coverage.reportPaths=coverage.xml